name: Codestyle

on: [push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-modules
        with:
          path: |
            ./lab3/node_modules
            ./lab3/yarn.lock
          key: ${{ hashFiles('./lab3/yarn.lock') }}

      - if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        name: Install modules
        run: |
          cd lab3
          yarn
  eslint:
    name: ESLint
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-modules
        with:
          path: |
            ./lab3/node_modules
            ./lab3/yarn.lock
          key: ${{ hashFiles('./lab3/yarn.lock') }}

      - name: Run ESLint
        run: |
          cd lab3
          yarn lint
  prettier:
    name: Prettier
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-modules
        with:
          path: |
            ./lab3/node_modules
            ./lab3/yarn.lock
          key: ${{ hashFiles('./lab3/yarn.lock') }}

      - name: Run Prettier
        run: |
          cd lab3
          yarn format:check
